name = "involvex-claude-router-cloud"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
account_id = "d4e0f1c1c830642168db2f4ea3aece58"

[alias]
"@/lib/usageDb.js" = "./src/stubs/usageDb.js"

# Step 3: Paste your KV & D1 IDs here
[[kv_namespaces]]
binding = "KV"
id = "6c35877893164e48b849f001d129cabd"

[[d1_databases]]
binding = "proxy_db"
database_name = "proxy-db"
database_id = "04d00543-2f72-4834-9c69-3f8e3fe184c3"
